### PR TITLE
Example makefile for prox_reporter project

### PR DESCRIPTION
**Pull request by pkmurphy-renesas**

### CODE REVIEW

**Comment by blauret** [comment]
@pkmurphy-renesas, Sorry we're lagging in reviewing that. We'll work on it ASAP

**Comment by pkmurphy-renesas** [comment]
@blauret, anything else I need to do before this is reviewed/merged? I think the build-check-deploy action may be failing as this pull request originated from a fork of the repo. Need me to move the changes to a branch of this repo and do a new pull request?

**Comment by koen-vdm** [comment]
Hello @pkmurphy-renesas,
The checks for this pull request are failing because the merge is from your private GitHub where there are no valid AWS credentials configured. This can be fixed by first merging your private repo onto a branch of this repo (for which you do not need to pass any checks) and then merging that branch into the main.

**Comment by pkmurphy-renesas** [comment]
Closing this pull request. Will merge into another branch of this repo and initiate a new pull request from it.

**Pull request closed without merging**
